package lightning.config;

import java.util.List;
import java.util.concurrent.TimeUnit;

import javax.annotation.Nullable;

import com.google.common.collect.ImmutableList;

import lightning.mail.Mail;

public class Config {
  @Override
  public String toString() {
    return "Config [autoReloadPrefixes=" + autoReloadPrefixes + ", scanPrefixes=" + scanPrefixes
        + ", ssl=" + ssl + ", server=" + server + ", mail=" + mail + ", db=" + db
        + ", enableDebugMode=" + enableDebugMode + "]";
  }
  
  // Whether or not to enable debug mode.
  // Recommended for development, DO NOT LEAVE ON IN PRODUCTION!
  // Enables automatic hot swapping (reloading) of handler classes, exception stack traces in
  // the browser, and disables HTTP caching of static files. Ensures templates and static files
  // will always be reloaded from disk on each request. Essentially: quick and easy save and
  // refresh development.
  public boolean enableDebugMode = false;

  // A list of prefixes on which classes should be automatically reloaded on each incoming
  // request in DEBUG MODE ONLY.
  public List<String> autoReloadPrefixes = ImmutableList.of();
  
  // A list of prefixes in which to search for routes, websockets, exception handlers, etc.
  public List<String> scanPrefixes = ImmutableList.of();
  
  public SSLConfig ssl = new SSLConfig();
  public ServerConfig server = new ServerConfig();
  public MailConfig mail = new MailConfig();
  public DBConfig db = new DBConfig();
  
  public static final class SSLConfig {
    @Override
    public String toString() {
      return "SSLConfig [keyStoreFile=" + keyStoreFile + ", keyStorePassword=" + keyStorePassword
          + ", trustStoreFile=" + trustStoreFile + ", trustStorePassword=" + trustStorePassword
          + "]";
    }

    // For the Java Key Store (JKS):
    public @Nullable String keyStoreFile;       // Required to enable SSL.
    public @Nullable String keyStorePassword;   // Required to enable SSL.
    public @Nullable String trustStoreFile;     // Optional.
    public @Nullable String trustStorePassword; // Optional.
    
    // Whether to redirect HTTP requests to their HTTPS equivalents.
    // If true, this server will also install an HTTP server (on server.port)
    public boolean redirectInsecureRequests = true;
    
    // If SSL is enabled, the server will listen for HTTPS connections on
    // this port.
    public int port = 443;
    
    public boolean isEnabled() {
      return keyStorePassword != null && keyStoreFile != null;
    }
  }
  
  public static final class ServerConfig {
    @Override
    public String toString() {
      return "ServerConfig [hmacKey=" + hmacKey + ", port=" + port + ", minThreads=" + minThreads
          + ", maxThreads=" + maxThreads + ", threadTimeoutMs=" + threadTimeoutMs
          + ", websocketTimeoutMs=" + websocketTimeoutMs + ", staticFilesPath=" + staticFilesPath
          + ", templateFilesPath=" + templateFilesPath + ", trustLoadBalancerHeaders="
          + trustLoadBalancerHeaders + "]";
    }
    
    // Encryption key for verifying integrity of hashes generated by the server.
    // Should be something long, random, secret, and unique to your app.
    public String hmacKey;
    
    // Port on which to listen for incoming HTTP connections.
    public int port = 80;
    
    // Minimum number of handler threads.
    public int minThreads = 40;
    
    // Maximmum number of handler threads.
    public int maxThreads = 250;
    
    // Jetty handler thread timeout.
    public int threadTimeoutMs = (int) TimeUnit.SECONDS.toMillis(60);
    
    // Jetty websocket timeout.
    public int websocketTimeoutMs = (int) TimeUnit.SECONDS.toMillis(60); // For websockets.
    
    // Maximum incoming request size (in bytes).
    public int maxPostBytes = 2000000; // In bytes
    
    // Maxmimum number of query parameters on an incoming request (in #).
    public int maxQueryParams = 100; // In number of params.
    
    // Maximum amount of time allowed before closing an idle HTTP connection.
    public int connectionIdleTimeoutMs = (int) TimeUnit.MINUTES.toMillis(3);
    
    // Path from which to serve static files.
    public String staticFilesPath; // Relative to src/main|resources/java in your eclipse project folder.
    
    // Path in which freemarker templates are located.
    public String templateFilesPath; // Relative to src/main|resources/java in your eclipse project folder.
    
    // Host on which to listen.
    public String host = "0.0.0.0";
    
    // Whether or not to trust load balancer headers (X-Forwarded-From, X-Forwarded-For, X-Forwarded-Proto).
    // Enable only if your app is firewalled behind a load balancer.
    // TODO: Implement this.
    public boolean trustLoadBalancerHeaders = false;
    
    // Maximum size of a cached static file in bytes.
    public int maxCachedStaticFileSizeBytes = 1024 * 50; // 50KB
    
    // Maxmimum size of the static file cache in bytes.
    public int maxStaticFileCacheSizeBytes = 1024 * 1024 * 30; // 30MB
    
    // Maximum number of cached static files.
    public int maxCachedStaticFiles = 500;
  }
  
  public static final class MailConfig implements Mail.MailConfig {
    @Override
    public String toString() {
      return "MailConfig [useSSL=" + useSSL + ", address=" + address + ", username=" + username
          + ", password=" + password + ", host=" + host + ", port=" + port + "]";
    }

    // Whether or not to use SMTP over SSL.
    public boolean useSSL = true;
    
    // Email address
    public @Nullable String address;
    
    // SMTP login
    public @Nullable String username;
    
    // SMTP password
    public @Nullable String password;
    
    // SMTP host
    public @Nullable String host;
    
    // SMTP port
    public int port = 465;
    
    public boolean isEnabled() {
      return host != null && username != null;
    }
    
    @Override
    public String getAddress() {
      return address;
    }
    
    @Override
    public int getPort() {
      return port;
    }
    
    @Override
    public boolean useSSL() {
      return useSSL;
    }
    
    @Override
    public String getHost() {
      return host;
    }
    
    @Override
    public String getUsername() {
      return username;
    }
    
    @Override
    public String getPassword() {
      return password;
    }
  }
  
  public static final class DBConfig {
    @Override
    public String toString() {
      return "DBConfig [host=" + host + ", port=" + port + ", username=" + username + ", password="
          + password + ", name=" + name + "]";
    }
    
    // MySQL database host
    public String host = "localhost";
    
    // MySQL database port
    public int port = 3306;
    
    // MySQL database username
    public String username = "httpd";
    
    // MySQL database password
    public String password = "httpd";
    
    // MySQL database anme
    public String name;
  }
}
